### ISSUE TITLE
'Create your spotify application' causes an invalid_client error

### ISSUE THREAD

**Issue by SCdF** [citelao/Spotify-for-Alfred#86]
Alfred v3.3.1

When I select `Create your spotify application` I get the following error in the debug trace:

```
Starting debug for 'Spotifious'

[2017-03-15 12:20:31][ERROR: action.script] Fatal error: Uncaught exception 'SpotifyWebAPI\SpotifyWebAPIException' with message 'invalid_client' in /Users/scdf/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.F9D777CB-FFC5-4141-AD3F-1049F4B3AF83/vendor/jwilsson/spotify-web-api-php/src/Request.php:120
Stack trace:
#0 /Users/scdf/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.F9D777CB-FFC5-4141-AD3F-1049F4B3AF83/vendor/jwilsson/spotify-web-api-php/src/Request.php(21): SpotifyWebAPI\Request->send('POST', 'https://account...', Array, Array)
#1 /Users/scdf/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.F9D777CB-FFC5-4141-AD3F-1049F4B3AF83/vendor/jwilsson/spotify-web-api-php/src/Session.php(148): SpotifyWebAPI\Request->account('POST', '/api/token', Array, Array)
#2 /Users/scdf/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.F9D777CB-FFC5-4141-AD3F-1049F4B3AF83/src/citelao/Spotifious/Spotifious.php(339): SpotifyWebAPI\Ses in /Users/scdf/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.F9D777CB-FFC5-4141-AD3F-1049F4B3AF83/vendor/jwilsson/spotify-web-api-php/src/Request.php on line 120
```

**Comment by dubstrike** [comment]
Same here. Most recent release + Alfred v3.3.1 [806] on OS X 10.11.6
```
Starting debug for 'Spotifious'

[2017-03-15 22:40:02][input.scriptfilter] Processing output of 'action.revealfile' with arg 'appsetup⟩'
[2017-03-15 22:40:02][input.scriptfilter] Processing output of 'action.script' with arg 'appsetup⟩'
[2017-03-15 22:40:04][ERROR: action.script] PHP Fatal error:  Uncaught exception 'SpotifyWebAPI\SpotifyWebAPIException' with message 'invalid_client' in /Users/Wojtek/Documents/Alfred Prefs/Alfred.alfredpreferences/workflows/user.workflow.9D77035D-DD32-4E99-A211-9F82E60E6D19/vendor/jwilsson/spotify-web-api-php/src/Request.php:120
Stack trace:
#0 /Users/Wojtek/Documents/Alfred Prefs/Alfred.alfredpreferences/workflows/user.workflow.9D77035D-DD32-4E99-A211-9F82E60E6D19/vendor/jwilsson/spotify-web-api-php/src/Request.php(21): SpotifyWebAPI\Request->send('POST', 'https://account...', Array, Array)
#1 /Users/Wojtek/Documents/Alfred Prefs/Alfred.alfredpreferences/workflows/user.workflow.9D77035D-DD32-4E99-A211-9F82E60E6D19/vendor/jwilsson/spotify-web-api-php/src/Session.php(148): SpotifyWebAPI\Request->account('POST', '/api/token', Array, Array)
#2 /Users/Wojtek/Documents/Alfred Prefs/Alfred.alfredpreferences/workflows/user.workflow.9D77035D-DD32-4E99-A211-9F82E60E6D19/src/citelao/Spotifious/Spotifious.php(339): SpotifyWebAPI\Session->refreshToken()
#3 /Users/Wojtek/Documents/ in /Users/Wojtek/Documents/Alfred Prefs/Alfred.alfredpreferences/workflows/user.workflow.9D77035D-DD32-4E99-A211-9F82E60E6D19/vendor/jwilsson/spotify-web-api-php/src/Request.php on line 120
Fatal error: Uncaught exception 'SpotifyWebAPI\SpotifyWebAPIException' with message 'invalid_client' in /Users/Wojtek/Documents/Alfred Prefs/Alfred.alfredpreferences/workflows/user.workflow.9D77035D-DD32-4E99-A211-9F82E60E6D19/vendor/jwilsson/spotify-web-api-php/src/Request.php:120
Stack trace:
#0 /Users/Wojtek/Documents/Alfred Prefs/Alfred.alfredpreferences/workflows/user.workflow.9D77035D-DD32-4E99-A211-9F82E60E6D19/vendor/jwilsson/spotify-web-api-php/src/Request.php(21): SpotifyWebAPI\Request->send('POST', 'https://account...', Array, Array)
#1 /Users/Wojtek/Documents/Alfred Prefs/Alfred.alfredpreferences/workflows/user.workflow.9D77035D-DD32-4E99-A211-9F82E60E6D19/vendor/jwilsson/spotify-web-api-php/src/Session.php(148): SpotifyWebAPI\Request->account('POST', '/api/token', Array, Array)
#2 /Users/Wojtek/Documents/Alfred Prefs/Alfred.alfredpreferences/workflows/user.workflow.9D77035D-DD32-4E99-A211-9F82E60E6D19/src/citelao/Spotifious/Spotifious.php(339): SpotifyWebAPI\Session->refreshToken()
#3 /Users/Wojtek/Documents/ in /Users/Wojtek/Documents/Alfred Prefs/Alfred.alfredpreferences/workflows/user.workflow.9D77035D-DD32-4E99-A211-9F82E60E6D19/vendor/jwilsson/spotify-web-api-php/src/Request.php on line 120
```

**Comment by citelao** [comment]
Take a look at https://github.com/citelao/Spotify-for-Alfred/raw/dev/dist/Spotifious.alfredworkflow

**Comment by SCdF** [comment]
That fixes it, thanks!
